### PR TITLE
Add phar & imap extension stuff to work on

### PR DESCRIPTION
**Pull request by bishopb**
I've got a few long-view phar and imap changes I'd like to see
done, but they're not prioritized on my list b/c bugs come first
(and there are a _lot_ of bugs :) Great opportunity for someone
to jump in and get in on the ground floor.

### CODE REVIEW

**Comment by Danack** [comment]
Hey @bishopb,

Thanks for that. Apologies - I probably should have made it clearer that I was moving where I'm going to hold this info over to https://github.com/Danack/RfcCodex/blob/master/project_coordination.md to make it even easier for myself or other people to edit them, and avoid spending time on writing code.

I've put the ones you added there - please could you do me a favour and give me a link to where people can have discussions about what needs to be done for those things?

If you just setup a blank github repo, that has some details of the work  in it's readme, that would be great. That will allow people to ask questions, or for you to list individual pieces of work to be done.

**Comment by bishopb** [comment]
Gotcha, thanks for migrating to the correct location.

I dug through the PHP.net Wiki and that seems like a good place to house this and to use bugs.php.net as the discussion vehicle. If/when momentum builds, I can switch us to a better tool.

Phar: https://wiki.php.net/todo/ext/phar
Imap: https://wiki.php.net/todo/ext/imap

**Comment by Danack** [comment]
Could you do me a favour an open one issue or wiki page for each of those, and braindump your thoughts there, so that I can link to them?

**Comment by bishopb** [comment]
Sure.

* For the phar task: https://bugs.php.net/bug.php?id=78571
* For the imap task: https://bugs.php.net/bug.php?id=78572

The IMAP task had discussion start within _minutes_ of its posting. That, to me, validates using bugs.php.net as the discussion repository, at least until the single-thread format becomes untenable.

**Comment by Danack** [comment]
> That, to me, validates using bugs.php.net as the discussion repository

It's definitely a good choice for that type of work.

I think for other stuff e.g. more userland facing, or need to get 'buy-in' from lots of people, other places might be better.

That's why I'm just asking people to submit a link to be added to the https://github.com/Danack/RfcCodex/blob/master/project_coordination.md doc, rather than telling them to use a particular place for discussion.

For discoverability purpose some things need to be centralised, but then for convenience other stuff needs to be decentralised......probably.

Anyway, thanks for the links - added to the doc now.

**Comment by bishopb** [comment]
Agreed all around. Thanks for all you do!

**Pull request closed without merging**
